-- IT Passport Vocabulary Seed Data
-- Generated from deepseek_csv_20260507_17bc21.txt
-- Total: 179 words across 6 pages

INSERT INTO words (id, page_num, word, full_name, overview_en, overview_jp, usage, examples, quick_memory_en, quick_memory_jp, studied)
VALUES
  (1, 1, '3C分析', '', 'A strategic framework analyzing three customer variables: Customer, Competitor, and Company.', '顧客・競合・自社の3つの要素を分析する戦略フレームワーク (こきゃく・きょうごう・じしゃ)', 'Used in marketing strategy to understand market position and find competitive advantages.', ', New product launch planning , Market entry strategy for startups , Annual marketing strategy review', '3C = Customer, Competitor, Company.', '3C = 顧客・競合・自社', false),,
  (2, 1, 'ASP (Application Service Provider)', '', 'A company that provides software applications over the internet.', 'インターネット経由でソフトウェアを提供する事業者 (アプリケーションサービスプロバイダ)', 'Used by businesses to rent software instead of buying and installing it locally.', ', Salesforce CRM as a service , QuickBooks Online for accounting , Google Workspace for email and docs', 'Software rental over internet.', 'ソフトを借りて使う仕組み', false),,
  (3, 1, 'BCP (Business Continuity Plan)', '', 'A plan to keep business running during disasters or major disruptions.', '災害時も事業を続けるための計画 (ビジネス・コンティニュイティ・プラン)', 'Used by companies to prepare for earthquakes, cyberattacks, pandemics, or system failures.', ', Data backup at remote site , Alternate office setup , Employee communication protocol during crisis', 'Keep business alive during disaster.', '災害時に事業を止めない計画', false),,
  (4, 1, 'BPM (Business Process Management)', '', 'A discipline to improve, manage, and automate business processes.', '業務プロセスを改善・管理・自動化する手法 (ビジネス・プロセス・マネジメント)', 'Used to make workflows more efficient, reduce errors, and cut costs.', ', Invoice approval automation , Customer complaint handling流程 , Employee onboarding process redesign', 'Manage and improve workflows.', '業務の流れを良くする管理', false),,
  (5, 1, 'BPO (Business Process Outsourcing)', '', 'Contracting business operations to an external provider.', '業務を外部会社に委託すること (ビジネス・プロセス・アウトソーシング)', 'Used to reduce costs and focus on core business by outsourcing non-core tasks.', ', Payroll processing to ADP , Call center operations to a third party , IT helpdesk outsourcing', 'Hire others to do back-office work.', '業務を外注すること', false),,
  (6, 1, 'BPR (Business Process Reengineering)', '', 'Radically redesigning business processes from scratch for major improvements.', '業務プロセスを根本から再設計すること (ビジネス・プロセス・リエンジニアリング)', 'Used when a company needs dramatic cost reduction, quality improvement, or speed increase.', ', Ford''s procurement process redesign , Insurance claim processing overhaul , Bank loan approval simplification', 'Start from zero to transform processes.', 'ゼロから業務を組み直す', false),,
  (7, 1, 'BSC (Balanced Scorecard)', '', 'A strategic performance management framework with four perspectives: Financial, Customer, Internal Process, Learning & Growth.', '財務・顧客・内部プロセス・学習成長の4視点で業績を測る手法 (バランスト・スコアカード)', 'Used to translate company strategy into measurable KPIs across all departments.', ', Retail chain tracking customer satisfaction , Manufacturer monitoring production efficiency , Hospital measuring patient care quality', 'Measure strategy from four angles.', '4つの視点で経営を評価', false),,
  (8, 1, 'BTO (Build to Order)', '', 'Manufacturing products only after receiving customer orders.', '注文を受けてから生産する方式 (ビルド・トゥ・オーダー)', 'Used to reduce inventory risk and customize products to customer needs.', ', Dell computers built per order , Custom car manufacturing , Tailored suit production', 'Make after order, not before.', '受注してから作る生産方式', false),,
  (9, 1, 'BYOD (Bring Your Own Device)', '', 'Company policy allowing employees to use personal devices for work.', '従業員の私物端末を仕事に使うことを許可する方針 (ブリング・ユア・オウン・デバイス)', 'Used in companies to reduce hardware costs and let employees work on familiar devices.', ', Using personal iPhone for work email , Laptop with company VPN access , Bringing tablet to meetings for notes', 'Work from your own phone/PC.', '自分の端末を仕事で使う', false),,
  (10, 1, 'CA (Certificate Authority)', '', 'A trusted entity that issues digital certificates for secure communication.', 'デジタル証明書を発行する信頼できる機関 (じゅしょうにんしょうきかん / 証明機関)', 'Used to verify website identity and enable HTTPS for secure browsing.', ', VeriSign issuing SSL certificates , Let''s Encrypt free certificates , Company internal CA for employee IDs', 'Issuer of digital ID cards for websites.', '電子証明書の発行機関', false),,
  (11, 1, 'CAD (Computer-Aided Design)', '', 'Software for creating precise 2D or 3D technical drawings.', 'コンピュータを使って設計図を作成するソフト (キャド)', 'Used by engineers, architects, and product designers to create and modify designs digitally.', ', AutoCAD for architectural plans , SolidWorks for mechanical parts , Fusion 360 for 3D printing models', 'Digital drawing tool for designers.', '設計図をパソコンで作る', false),,
  (12, 1, 'CAPTCHA', '', 'A test to tell humans and bots apart, often distorted text or image selection.', '人間とbotを区別するテスト (キャプチャ)', 'Used on websites to prevent automated spam, fake account creation, and brute-force attacks.', ', Selecting traffic lights in images , Typing distorted letters for login , Checkbox \I am not a robot\', 'Human-or-bot test.', '人間かbotかを確かめる', false),,
  (13, 1, 'CEO (Chief Executive Officer)', '', 'The highest-ranking executive in a company, responsible for major decisions.', '会社の最高経営責任者 (さいこうけいえいせきにんしゃ / シーイーオー)', 'Leads company strategy, represents the company to board and public, and has final authority.', ', Tim Cook of Apple , Satya Nadella of Microsoft , Founder-CEO of a startup', 'Top boss of a company.', '会社のトップ', false),,
  (14, 1, 'CIO (Chief Information Officer)', '', 'The executive in charge of IT strategy and computer systems.', 'IT戦略と情報システムを統括する役職 (最高情報責任者 / さいこうじょうほうせきにんしゃ)', 'Used to align technology investments with business goals and manage IT risks.', ', Migrating company to cloud , Leading digital transformation , Overseeing cybersecurity strategy', 'Boss of company IT.', 'IT全体の責任者', false),,
  (15, 1, 'CRM (Customer Relationship Management)', '', 'A strategy and software system to manage interactions with customers.', '顧客関係管理 (こきゃくかんけいかんり / シーアールエム)', 'Used by sales, marketing, and support teams to track leads, manage contacts, and analyze customer data.', ', Salesforce tracking sales pipeline , HubSpot managing email campaigns , Zendesk handling support tickets', 'Manage customer interactions systematically.', '顧客情報を一括管理', false),,
  (16, 1, 'CSF (Critical Success Factor)', '', 'Key activities or conditions necessary for an organization to achieve its mission.', '組織が成功するために不可欠な要素 (クリティカル・サクセス・ファクター)', 'Used in strategic planning to identify what must go right for the business to succeed.', ', For an airline: on-time departures , For an e-commerce site: website uptime , For a hospital: patient safety', 'Must-have conditions for success.', '成功に必須の条件', false),,
  (17, 1, 'CSIRT (Computer Security Incident Response Team)', '', 'A specialized team that handles cybersecurity incidents and breaches.', 'サイバーセキュリティ事故に対応する専門チーム (シーサート)', 'Used to detect, analyze, contain, and recover from cyberattacks or system compromises.', ', Responding to ransomware attack , Investigating data breach , Managing DDoS attack mitigation', 'Cyber emergency response team.', 'セキュリティ事故対応チーム', false),,
  (18, 1, 'CSR (Corporate Social Responsibility)', '', 'A self-regulating business model that holds companies accountable to society and environment.', '企業の社会的責任 (きぎょうのしゃかいてきせきにん)', 'Used by companies to improve public image, meet regulations, and attract responsible investors.', ', Reducing carbon emissions , Fair labor practices in supply chain , Donating percentage of profits to charity', 'Business doing good for society.', '会社の社会に対する責任', false),,
  (19, 1, 'DFD (Data Flow Diagram)', '', 'A diagram showing how data moves through a system, including sources, processes, and destinations.', 'データの流れを図示したもの (データ・フロー・ダイアグラム)', 'Used by system analysts to document existing systems or design new ones.', ', Order processing system diagram , Student registration flow chart , ATM withdrawal data movement', 'Map of data movement in a system.', 'データの流れ図', false),,
  (20, 1, 'DRAM (Dynamic Random Access Memory)', '', 'A type of computer memory that stores each bit in a capacitor, requiring constant refresh.', 'コンピュータの主記憶装置の一種 (ディーラム / ダイナミックRAM)', 'Used as the main memory (RAM) in computers, smartphones, and game consoles.', ', DDR4 RAM in laptops , GDDR6 in graphics cards , LPDDR in smartphones', 'Main memory that needs refreshing.', 'パソコンの主記憶', false),,
  (21, 1, 'EA (Enterprise Architecture)', '', 'A framework that aligns business strategy with IT infrastructure and processes.', 'ビジネス戦略とITを整合させる設計手法 (エンタープライズ・アーキテクチャ)', 'Used by large organizations to manage complexity and guide technology investments.', ', TOGAF framework implementation , Government digital transformation planning , Banking system integration after merger', 'Blueprint for business + IT alignment.', '会社全体の設計図', false),,
  (22, 1, 'ERP (Enterprise Resource Planning)', '', 'Integrated software for managing core business processes like finance, HR, and supply chain.', '基幹業務システム (きかんぎょうむシステム / イーアールピー)', 'Used to unify data across departments into a single database, eliminating silos.', ', SAP for multinational corporations , Oracle NetSuite for mid-size firms , Microsoft Dynamics 365', 'All-in-one business software.', '会社全体の統合システム', false),,
  (23, 1, 'E-R図 (Entity Relationship Diagram)', '', 'A diagram showing entities (data tables) and relationships between them.', 'テーブル間の関係を図示したデータベース設計図 (イーアールず)', 'Used by database designers to model data structure before building a database.', ', Customer-Order-Product relationship model , Library book-lending system design , Hospital patient-record schema', 'Database relationship picture.', 'データベースの関係図', false),,
  (24, 1, 'FP法 (Function Point Method)', '', 'A method to measure software size based on user-requested functions, not lines of code.', 'ユーザー機能からソフトウェア規模を測定する手法 (ファンクションポイントほう)', 'Used to estimate project cost, effort, and duration in early development stages.', ', Calculating development cost for banking app , Comparing productivity across teams , Outsourcing contract pricing', 'Measure software by its features.', '機能ベースのソフト規模測定', false),,
  (25, 1, 'HTML (HyperText Markup Language)', '', 'The standard language for creating web pages using tags to structure content.', 'ウェブページを作るための標準言語 (エイチティーエムエル)', 'Used by web developers to structure text, images, links, and forms on websites.', ', Creating a blog post with headings and paragraphs , Building a product catalog with images , Designing a contact form', 'Language for building web pages.', 'ホームページを作る言語', false),,
  (26, 1, 'ICT (Information and Communication Technology)', '', 'An umbrella term for all technologies used to handle information and communication.', '情報通信技術 (じょうほうつうしんぎじゅつ)', 'Used in education, business, and government to enable digital communication and data processing.', ', School tablets and online learning platforms , Video conferencing for remote work , Government digital ID systems', 'All tech for info + communication.', '情報と通信の技術全般', false),,
  (27, 1, 'IDS (Intrusion Detection System)', '', 'A security tool that monitors network traffic and alerts on suspicious activity.', '不正侵入を監視して警告するシステム (いんたんじょんおう)', 'Used to detect cyberattacks but does not block them automatically (unlike IPS).', ', Snort open-source IDS , Alerting on multiple failed logins , Detecting port scanning activity', 'Alarm system for cyberattacks.', '侵入を検知して警告', false),,
  (28, 1, 'IoT (Internet of Things)', '', 'A network of physical devices (not just computers) connected to the internet.', 'モノのインターネット (もののインターネット)', 'Used to collect data, enable remote control, and automate physical objects.', ', Smart thermostat adjusting temperature remotely , Fitbit tracking health data to phone , Factory sensors predicting machine failure', 'Internet-connected everyday objects.', 'モノをネットに繋ぐ', false),,
  (29, 1, 'IPS (Intrusion Prevention System)', '', 'A security system that detects AND blocks suspicious network activity in real-time.', '不正侵入を検知して遮断するシステム (いんたんじょんおう)', 'Used in corporate networks to actively stop attacks, placed inline with traffic flow.', ', Blocking known attack signatures , Dropping malicious packets , Preventing SQL injection attempts', 'Detect + block attacks in real-time.', '侵入を検知して防ぐ', false),,
  (30, 1, 'IP Address (Internet Protocol Address)', '', 'A unique numeric label assigned to each device on a network for identification and location.', 'ネットワーク上の機器を識別する番号 (アイピーアドレス)', 'Used to route data between devices on the internet or local networks.', ', 192.168.1.1 for home router , IPv4 like 203.0.113.5 , IPv6 like 2001:db8::1', 'Phone number for devices on a network.', '機器のネットワーク住所', false),;