-- IT Passport Vocabulary Seed Data
-- Generated from deepseek_csv_20260507_17bc21.txt
-- Total: 179 words across 6 pages

INSERT INTO words (id, page_num, word, full_name, overview_en, overview_jp, usage, examples, quick_memory_en, quick_memory_jp, studied)
VALUES
  (61, 3, 'スパイラルモデル (Spiral Model)', '', 'A software development model combining prototyping and waterfall with a focus on risk analysis in iterative cycles.', 'リスク分析を重視し、螺旋状に繰り返しながら開発を進めるモデル (スパイラルモデル)', 'Used for large, complex, high-risk projects where requirements are unclear.', ', NASA space system development , Large-scale government IT project , Medical device software', 'Risk-driven iterative development loop.', 'リスク分析を繰り返す開発手法', false),,
  (62, 3, 'スプーリング (Spooling)', '', 'A process that holds data temporarily in a buffer (like memory or disk) while a slower device, like a printer, catches up.', '低速な周辺機器のためにデータを一時的に蓄積する仕組み (スプーリング)', 'Used to free up the CPU so it doesn''t have to wait for slower I/O devices.', ', Sending multiple documents to a network printer , Reading data from a CD-ROM while playing music , Input from a keyboard to the CPU', 'Buffering data for slow devices.', '低速機器のための一時データ蓄積', false),,
  (63, 3, 'スループット (Throughput)', '', 'The amount of work or data a system processes successfully over a given period of time.', '単位時間あたりに処理できる仕事量 (スループット)', 'Used to measure performance of networks, CPUs, assembly lines, etc.', ', Network: 100 Mbps data transfer , Factory: 500 cars per day , Server: 10,000 requests/minute', 'Actual work done per unit time.', '単位時間あたりの処理量', false),,
  (64, 3, 'ターンアラウンドタイム (Turnaround Time)', '', 'The total time between submitting a job to a system and receiving the completed result.', '処理を依頼してから結果を受け取るまでの総時間 (ターンアラウンドタイム)', 'Used in batch processing, user experience, and operational efficiency.', ', Time to compile and run a program , Time from laundry drop-off to pickup , Time from order to product delivery', 'Request-to-result total time.', '依頼から完了までの全時間', false),,
  (65, 3, 'チェックディジット (Check Digit)', '', 'An extra digit added to a number to detect common data entry errors like typos or digit swaps.', '入力ミスを検出するために追加される数字 (チェックディジット)', 'Used in barcodes, credit card numbers, and identification codes.', ', UPC barcode on products , ISBN number on books , Credit card number validation', 'Error-detecting extra digit.', '入力誤り発見のための数字', false),,
  (66, 3, '著作権 (Copyright)', '', 'A legal right giving the creator of original work exclusive rights to its use and distribution for a limited time.', '著作物を保護する法律上の権利 (ちょさくけん)', 'Used to control copying, public performance, and adaptation of creative works.', ', Music on Spotify not free to download , Movie not allowed to record in theater , Software license terms', 'Creator controls the work legally.', '創作物を守る権利', false),,
  (67, 3, 'ディジタルデバイド (Digital Divide)', '', 'The gap between those who have access to modern information technology and those who do not.', '情報技術を利用できる人とできない人の差 (ディジタルデバイド)', 'Used in social policy to address inequality in internet access and digital literacy.', ', Urban vs rural broadband access , Elderly struggling with online banking , Low-income students without laptops', 'Technology access gap.', 'IT利用の格差問題', false),,
  (68, 3, 'データウェアハウス (Data Warehouse)', '', 'A large, centralized storage system that collects data from multiple sources for analysis and reporting.', '分析用に複数のデータ源から集めた大規模データベース (データウェアハウス)', 'Used by businesses for business intelligence, historical analysis, and data mining.', ', Amazon analyzing purchase history , Hospital aggregating patient records , Bank consolidating transaction data', 'Central data store for analysis.', '分析用の巨大データ倉庫', false),,
  (69, 3, 'データマート (Data Mart)', '', 'A smaller, focused subset of a data warehouse designed for a specific team or department.', '特定の部署向けに作られた小規模なデータウェアハウス (データマート)', 'Used when a department needs quick access to tailored data without navigating the whole warehouse.', ', Sales team''s regional sales mart , Marketing campaign performance mart , Finance department budget mart', 'Department-sized data warehouse.', '部署専用のデータ小売店', false),,
  (70, 3, 'データマイニング (Data Mining)', '', 'The process of discovering hidden patterns, correlations, and insights from large datasets.', '大量のデータから有益なパターンやルールを見つけること (データマイニング)', 'Used for market basket analysis, fraud detection, and customer segmentation.', ', Supermarket: beer & diapers together , Credit card company detecting fraud , Netflix recommending movies', 'Finding gold nuggets in data mountains.', 'データから価値ある情報を発掘', false),,
  (71, 3, 'デジタル署名 (Digital Signature)', '', 'A cryptographic technique that proves the authenticity and integrity of a digital message or document.', '電子文書の作成者と改ざんされていないことを証明する技術 (デジタルしょめい)', 'Used for secure emails, software distribution, and legal contracts.', ', Signing a PDF contract online , Microsoft verifying driver updates , SSL certificate on website', 'Digital proof of who signed and no tampering.', '電子文書の本人確認と改竄防止', false),,
  (72, 3, 'デジタルフォレンジックス (Digital Forensics)', '', 'The process of recovering and investigating data from digital devices, often for legal evidence.', '犯罪捜査の証拠としてデジタル機器からデータを復元・分析する技術 (デジタルフォレンジックス)', 'Used in criminal investigations, corporate internal investigations, and incident response.', ', Recovering deleted files from a hard drive , Tracing a hacker''s network activity , Investigating employee data theft', 'CSI for computers and phones.', 'デジタル機器の法科学的調査', false),,
  (73, 3, 'デファクトスタンダード (De Facto Standard)', '', 'A standard that becomes widely adopted by market popularity, not because it''s officially approved by a standards body.', '公式な規格ではなく、市場でよく使われるようになった事実上の標準 (デファクトスタンダード)', 'Used to describe technologies that won the market battle.', ', Microsoft Office file formats (.doc, .xls) , PDF by Adobe , Qwerty keyboard layout', 'Market-chosen winner standard.', '業界の事実上の標準', false),,
  (74, 3, 'デュアルシステム (Dual System)', '', 'A fault-tolerant system where two independent computer systems run the same job, and their outputs are compared.', '同じ処理を二つの独立したシステムで実行し、結果を照合する方式 (デュアルシステム)', 'Used in critical applications where errors are unacceptable, like financial or aerospace systems.', ', Airline reservation system , Stock exchange transaction matching , Nuclear reactor control system', 'Two computers, one result (checking each other).', '結果を照合する二重システム', false),,
  (75, 3, 'デュプレックスシステム (Duplex System)', '', 'A system with two identical components where one is active and the other is on standby, ready to take over if the primary fails.', '現用系と待機系を持ち、故障時に切り替えるシステム (デュプレックスシステム)', 'Used to ensure high availability for critical servers and networks.', ', Primary and backup web server , Standby database server ready to take over , Dual power supply in a server', 'Active + Standby for no downtime.', '予備機で高可用性を実現', false),,
  (76, 3, '電子商取引 (EC) (Electronic Commerce)', '', 'Buying and selling goods or services using the internet and digital transactions.', 'インターネットを介した商品やサービスの売買 (でんししょうとりひき / イーシー)', 'Used for online retail, digital payments, and online marketplaces.', ', Amazon shopping for clothes , Buying train tickets on a website , Paying for a subscription with PayPal', 'Doing business online.', 'インターネットでの売買', false),,
  (77, 3, '特許権 (Patent Right)', '', 'An exclusive right granted for an invention, preventing others from making, using, or selling it without permission.', '発明を独占的に利用できる権利 (とっきょけん)', 'Used to protect new technologies, drugs, and processes for a limited time (typically 20 years).', ', iPhone''s unique design patent , Pharmaceutical drug formula , Tesla''s electric vehicle battery patent', 'Inventor''s exclusive monopoly for a time.', '発明を独占する権利', false),,
  (78, 3, 'ナレッジマネジメント (Knowledge Management)', '', 'The systematic process of capturing, distributing, and using knowledge within an organization.', '組織内の知識を共有し活用するための管理手法 (ナレッジマネジメント)', 'Used to prevent reinventing the wheel and retain expertise when employees leave.', ', Company wiki for internal documentation , Lessons learned database after projects , Expert directory to find specialists', 'Not losing what your company knows.', '組織の知恵を貯めて活かす', false),,
  (79, 3, 'バイオメトリクス認証 (Biometrics Authentication)', '', 'Automatic identification of a person based on their unique physical or behavioral traits.', '体の特徴を使って本人を確認する技術 (バイオメトリクスにんしょう)', 'Used for security access, device unlocking, and identity verification.', ', iPhone Touch ID (fingerprint) or Face ID , Airport immigration e-gates , Office door fingerprint scanner', 'You are the password.', '体の特徴で本人確認', false),,
  (80, 3, 'パイプライン制御 (Pipeline Control)', '', 'A CPU technique where multiple instructions are overlapped in execution to improve processing speed.', 'CPUが命令を並行して処理する技術 (パイプラインせいぎょ)', 'Used in all modern processors to improve performance.', ', A washing machine: wash, rinse, spin overlap , Car factory assembly line , CPU executing fetch-decode-execute in stages', 'Assembly line for computer instructions.', '命令を段階的に並列処理', false),,
  (81, 3, 'ハウジングサービス (Housing Service)', '', 'A service where a customer places their own server in a provider''s data center, providing power, cooling, and network.', '自社のサーバをデータセンターに預けて運用するサービス (ハウジングサービス)', 'Used by companies that want to own hardware but avoid building their own data center.', ', Colocation at Equinix data center , Small business hosting own server , Web company renting rack space', 'Rent physical space for your own server.', '自前サーバを預けて運用', false),,
  (82, 3, '派遣契約 (Temporary Staffing Contract)', '', 'A contract where a staffing agency employs a worker and sends them to work temporarily at a client company.', '人材派遣会社が労働者を雇い、他の会社に派遣する契約 (はけんけいやく)', 'Used to fill temporary skill gaps, cover parental leave, or manage seasonal workload.', ', IT specialist for 3-month project , Receptionist covering sick leave , Warehouse worker for holiday season', 'You work for agency, report to client.', '派遣会社が労働者を送り込む契約', false),,
  (83, 3, 'バリアフリー (Barrier-free)', '', 'Design that eliminates physical obstacles to enable access for people with disabilities, elderly, or other mobility issues.', '障害や年齢に関わらず利用しやすい環境を作る考え方 (バリアフリー)', 'Used in architecture, product design, and public transportation.', ', Wheelchair ramps on sidewalks , Tactile paving for the blind , Closed captions on videos', 'Removing obstacles for all people.', '障害となるものを取り除く', false),,
  (84, 3, 'バリューチェーン (Value Chain)', '', 'A model that breaks down a company''s activities into primary and support activities that add value to the final product.', '製品やサービスに価値が付加される一連の企業活動 (バリューチェーン)', 'Used to analyze where a company can reduce costs or differentiate itself.', ', Starbucks: bean sourcing, roasting, store experience , Amazon: order, pick, pack, ship , Toyota: design, parts, assembly, service', 'Steps from raw material to customer value.', '価値が生まれる活動の連鎖', false),,
  (85, 3, 'パレート図・ABC分析 (Pareto Chart / ABC Analysis)', '', 'A chart showing bars in descending order with a cumulative line, based on the 80/20 rule (80% effects come from 20% causes).', '少数の要因が全体の大部分を占めるという分析手法 (パレートず / ABCぶんせき)', 'Used in quality control, inventory management, and to prioritize problems.', ', 80% of sales from 20% of products , 80% of complaints from 20% of issue types , A-items (high value) vs C-items (low value) in inventory', 'Focus on the vital few, not the trivial many.', '2割の要因で8割の結果を説明', false),,
  (86, 3, 'ファイアウォール (Firewall)', '', 'A network security system that monitors and controls incoming and outgoing traffic based on predetermined rules.', 'ネットワークの出入り口で通信を監視し遮断するシステム (ファイアウォール)', 'Used to protect internal networks from unauthorized external access.', ', Home router blocking suspicious IPs , Office network blocking social media , Cloud firewall protecting web server', 'Wall between internal network and internet.', 'ネットワークの出入り口番', false),,
  (87, 3, 'ファシリティマネジメント (Facility Management)', '', 'The management of buildings, infrastructure, and real estate to support an organization''s core operations.', '建物や設備を最適に管理する業務 (ファシリティマネジメント)', 'Used to reduce operating costs, ensure safety, and improve workspace efficiency.', ', Office cleaning and maintenance , Energy management for a building , Space planning for remote/hybrid work', 'Taking care of all buildings and property.', '施設・設備の総合管理', false),,
  (88, 3, 'ファブレス (Fabless)', '', 'A company that designs and sells hardware but outsources the actual manufacturing (fabrication).', '自社で製造工場を持たず、設計だけを行う企業戦略 (ファブレス)', 'Used in semiconductor industry to focus on chip design and avoid multi-billion dollar fab costs.', ', NVIDIA designing GPUs, TSMC manufacturing , Apple designing chips, TSMC making them , ARM licensing designs to producers', 'Design only, no factories.', '工場を持たない製造業', false),,
  (89, 3, 'フールプルーフ (Foolproof)', '', 'A design principle that makes it impossible to make mistakes, even if the user is careless or untrained.', '操作を間違えようとしても間違えられないように設計すること (フールプルーフ)', 'Used in safety-critical products, consumer goods, and industrial equipment.', ', USB plug that only fits one way (now) , Microwave won''t run with door open , Gas pump auto shut-off when tank full', 'Design against user stupidity.', 'バカでも間違えられない設計', false),,
  (90, 3, 'フェールセーフ (Fail-safe)', '', 'A design principle where a system defaults to a safe state when it fails, rather than causing damage or injury.', '故障時に安全な状態に自動的に移行する設計 (フェールセーフ)', 'Used in elevators, traffic lights, trains, and industrial machinery.', ', Elevator brakes engage when cable fails , Traffic lights turn red flashing on power loss , Train doors close automatically if power fails', 'When broken, go to safe mode, not dangerous.', '壊れても安全側に倒れる', false),;