-- IT Passport Vocabulary Seed Data
-- Generated from deepseek_csv_20260507_17bc21.txt
-- Total: 179 words across 6 pages

INSERT INTO words (id, page_num, word, full_name, overview_en, overview_jp, usage, examples, quick_memory_en, quick_memory_jp, studied)
VALUES
  (91, 4, 'フェールソフト (Fail-soft)', '', 'A design where a system continues to operate at a reduced capacity after failure, rather than completely stopping.', '一部が故障しても全体は停止せず、能力を落として続行する設計 (フェールソフト)', 'Used in critical servers, networks, and services where some function is better than none.', ', Printer works in slow mode after paper jam sensor fails , Web server shows read-only mode if database fails , Phone works only for emergency calls if battery low', 'Fail, but keep working a bit.', '故障しても機能縮小で継続', false),,
  (92, 4, 'フォールトアボイダンス (Fault Avoidance)', '', 'A strategy to prevent faults from occurring during development by using high-quality components and rigorous design.', '開発段階で障害の発生を防ぐ品質対策 (フォールトアボイダンス)', 'Used in high-reliability systems like aerospace and medical devices.', ', Using military-grade components , Extreme testing before launch (NASA) , Coding with formal verification methods', 'Stop faults before they exist.', '故障を最初から作らない対策', false),,
  (93, 4, 'フォールトトレラント (Fault Tolerant)', '', 'A system''s ability to continue operating correctly even when one or more components fail.', '一部の部品が故障してもシステム全体は正常に動き続ける性質 (フォールトトレラント)', 'Used in critical systems like servers, aircraft, and spacecraft.', ', Airliner with 4 engines can fly with 1 failed , Server RAID with two disks , Spacecraft redundant navigation systems', 'Keep going correctly even when parts break.', '部品が壊れても動き続ける', false),,
  (94, 4, 'フォワードエンジニアリング (Forward Engineering)', '', 'The traditional software development process of going from high-level specifications to actual system implementation.', '設計から実装へ進む伝統的な開発プロセス (フォワードエンジニアリング)', 'Used in standard software development when starting from scratch.', ', Writing code from requirements document , Building a house from blueprints , Creating a database from ER diagram', 'Traditional design-then-build approach.', '仕様からコードを作る手法', false),,
  (95, 4, '不正アクセス禁止法 (Unauthorized Computer Access Act)', '', 'A Japanese law that prohibits unauthorized access to computer systems and punishes hacking activities.', '他人のコンピュータに無断でアクセスする行為を禁止する法律 (ふせいアクセスきんしほう)', 'Used in Japan to prosecute hackers, ID thieves, and those sharing illegal login credentials.', ', Sharing someone else''s password , Guessing another person''s login ID , Accessing server without permission', 'Japan''s anti-hacking law.', '不正なコンピュータアクセスを罰する法', false),,
  (96, 4, '不正競争防止法 (Unfair Competition Prevention Act)', '', 'A Japanese law that protects trade secrets and prevents unfair business practices like false claims, trademark infringement, and misappropriation.', '商標侵害や営業秘密の盗用など、不正な競争行為を禁止する法律 (ふせいきょうそうぼうしほう)', 'Used to protect intellectual property and fair market competition.', ', Stealing customer list from former employer , Fake luxury bags sold as real , Copying a competitor''s product design', 'Stop dirty business tricks.', '不正な競争手段を禁止する法', false),,
  (97, 4, 'プラグアンドプレイ (Plug and Play)', '', 'A technology that automatically detects and configures a new device when connected to a computer, without manual driver installation.', '周辺機器を接続するだけで使える技術 (プラグアンドプレイ)', 'Used for USB devices, monitors, printers, and external drives.', ', Plugging in a USB mouse - it just works , Connecting a monitor via HDMI , Inserting an SD card', 'Connect and use immediately.', '繋げばすぐに使える機能', false),,
  (98, 4, 'フラグメンテーション (Fragmentation)', '', 'The inefficient use of storage space where free space is broken into small, non-contiguous blocks over time.', 'ファイルの削除や作成を繰り返すことで記憶領域が細切れになる現象 (フラグメンテーション)', 'Occurs in file systems and memory, slowing down access speeds.', ', PC getting slower over time due to many writes , Hard drive needing defragmentation , Memory fragmentation causing app crashes', 'Storage space scattered like puzzle pieces.', '記憶領域の断片化', false),,
  (99, 4, 'ブラックボックステスト (Black-box Testing)', '', 'Software testing where the internal structure is not known; testers provide inputs and check outputs against requirements.', '内部構造を見ずに入力と出力だけでテストする手法 (ブラックボックステスト)', 'Used in acceptance testing, system testing, and by end-user testers.', ', Testing login: correct pass → success, wrong pass → error , Checking calculator app: 2+2=4 , Testing a website without knowing its code', 'Test from outside, like a user.', '内部を見ずに機能テスト', false),,
  (100, 4, 'フラッシュメモリ (Flash Memory)', '', 'A non-volatile memory that retains data without power, used for storage in USB drives and SSDs.', '電源が切れてもデータを保持できるメモリ技術 (フラッシュメモリ)', 'Used in USB drives, SD cards, solid-state drives (SSD), and smartphones.', ', SanDisk USB stick , MicroSD card for phone storage , Laptop SSD', 'Storage that keeps data when off.', '電源オフでも記憶を保持', false),,
  (101, 4, 'ブルーオーシャン戦略 (Blue Ocean Strategy)', '', 'A strategy to create a new, uncontested market space (blue ocean) rather than competing in an existing crowded market (red ocean).', '競争のない新しい市場を創造する経営戦略 (ブルーオーシャンせんりゃく)', 'Used when companies want to escape fierce competition and make competition irrelevant.', ', Cirque du Soleil (no animals, no stars) , Nintendo Wii (motion controls) , Yellow Tail wine (simple, fun wine)', 'Swim where no competitors exist.', '競争のない新市場を作れ', false),,
  (102, 4, 'ブレーンストーミング (Brainstorming)', '', 'A creative group technique where participants generate many ideas without criticism, then evaluate them later.', '批判を禁止して自由にアイデアを出す会議手法 (ブレーンストーミング)', 'Used in product development, problem-solving, and creative planning.', ', Post-it note session for new feature ideas , Weekly team creative meeting , Advertising campaign idea generation', 'No judgment, just lots of ideas first.', 'とにかく沢山アイデアを出す会議', false),,
  (103, 4, 'プロトタイプモデル (Prototype Model)', '', 'A software development approach where a working model is built early to refine requirements and get user feedback.', '試作品を作ってから本開発に入るモデル (プロトタイプモデル)', 'Used when requirements are unclear or user interface is critical.', ', Building a clickable app mockup for user testing , Showcasing a car clay model before production , Figma prototype for website approval', 'Build a rough model first to learn.', '試作→評価→完成を繰り返す', false),,
  (104, 4, 'プロバイダ責任制限法 (Provider Liability Limitation Act)', '', 'A Japanese law that limits the legal liability of internet service providers for content posted by users, as long as they follow removal procedures.', 'プロバイダが利用者の投稿による損害賠償責任を負わない条件を定めた法律 (プロバイダせきにんせいげんほう)', 'Used to balance free speech and victim protection online.', ', ISP not liable for defamatory user comments unless they refuse removal , Facebook''s content moderation policies , 2ch (5channel) comment liability rules', 'ISP not responsible if they remove bad content.', 'プロバイダの責任を制限する法', false),,
  (105, 4, 'ベンチマーキング (Benchmarking)', '', 'The practice of comparing your business processes and performance metrics to industry best practices or competitors.', '自社の製品やサービスを他社や業界標準と比較評価すること (ベンチマーキング)', 'Used to identify areas for improvement and set performance targets.', ', Airline comparing on-time performance against Delta , Restaurant comparing customer satisfaction to McDonald''s , Laptop speed compared to competitors', 'Measure yourself against the best.', '他社と比較して評価する', false),,
  (106, 4, 'ホスティングサービス (Hosting Service)', '', 'A service that provides server space, computing power, or infrastructure to host websites or applications.', 'Webサイトやアプリを公開するためのサーバスペースを提供するサービス (ホスティングサービス)', 'Used by individuals and companies to make their websites accessible on the internet.', ', Bluehost for WordPress site , AWS EC2 for custom application , GitHub Pages for static site', 'Rent space for your website.', 'Web公開のためのサーバ貸出', false),,
  (107, 4, 'ホワイトボックステスト (White-box Testing)', '', 'Software testing where the internal code structure is visible to the tester, allowing testing of paths, branches, and logic.', '内部構造を見てテストケースを作る手法 (ホワイトボックステスト)', 'Used by developers for unit testing and finding hidden errors.', ', Testing every if-else branch in code , Checking a loop runs exactly N times , Unit testing with code coverage tool', 'Test knowing the code inside.', '内部構造を考慮したテスト', false),,
  (108, 4, 'マーケティング (Marketing) (Target', '', 'One-to-one), Activities to promote and sell products', '', 'including target marketing (segmenting audiences) and one-to-one marketing (personalizing to individuals). JP: 顧客に合わせた販売促進活動 (マーケティング),Used to identify customer needs and deliver personalized value.,・Amazon personalized recommendations ・Email with your name and past purchases ・Ads showing shoes you browsed,EN: Right product to right person at right time. JP: 顧客一人ひとりに合わせた販売', '', '', '', false),,
  (109, 4, 'マイルストーン (Milestone)', '', 'A significant checkpoint or event in a project timeline that marks the completion of a major phase.', 'プロジェクトの重要な節目や段階を表す目印 (マイルストーン)', 'Used in project management to track progress and manage deadlines.', ', Project Kickoff (Milestone 1) , Alpha Version Complete (Milestone 2) , Final Delivery (Milestone 3)', 'Big checkpoints along the project road.', 'プロジェクトの重要な節目', false),,
  (110, 4, 'メーリングリスト (Mailing List)', '', 'A group of email addresses used to send a single message to many recipients simultaneously.', '同じメッセージを複数の受信者に同時送信するための仕組み (メーリングリスト)', 'Used for team announcements, newsletters, and discussion groups.', ', Company all-employees list , Classroom announcements to parents , Open source project developers list', 'One email to many people.', '同時に複数人へメール配信', false),,
  (111, 4, 'メモリインタリーブ (Memory Interleaving)', '', 'A technique that splits memory into multiple banks so the CPU can access them simultaneously, increasing speed.', 'メモリを複数の独立した区画に分けて並列アクセスする技術 (メモリインタリーブ)', 'Used in high-performance computing and gaming systems.', ', Dual-channel RAM on motherboards , Graphics card memory design , Supercomputer memory architecture', 'Access multiple memory sections at once.', '複数メモリを同時に読み書き', false),,
  (112, 4, '問題管理 (Problem Management)', '', 'The process of identifying and eliminating the root causes of recurring incidents to prevent future disruptions.', '繰り返し発生する障害の根本原因を特定し、再発を防止する管理プロセス (もんだいかんり)', 'Used in IT service management (ITIL) to reduce ticket volume and improve system stability.', ', Analyzing why servers crash every Tuesday , Fixing a bug causing login failures , Replacing faulty network cables causing drops', 'Stop problems from coming back (root cause fix).', '繰り返す障害の根本対策', false),,
  (113, 4, 'ユーザビリティ (Usability)', '', 'The ease of use and learnability of a product or system from the user''s perspective.', '製品やシステムの使いやすさ (ユーザビリティ)', 'Used in web design, app development, and product design.', ', Website with clear menu and search , App that can be used one-handed , Remote control with logical button layout', 'How easy something is to use.', '使いやすさの度合い', false),,
  (114, 4, 'ユニバーサルデザイン (Universal Design)', '', 'The design of products and environments to be usable by all people, regardless of age, ability, or status, without adaptation.', '年齢や能力に関わらず誰もが使いやすいように最初から設計する考え方 (ユニバーサルデザイン)', 'Used in architecture, product design, and public spaces.', ', Low-floor buses with ramp for everyone , Lever door handles (vs round knobs) , Curbs cuts for wheelchairs and strollers', 'Design for all people from the start.', '誰もが使いやすい設計', false),,
  (115, 4, 'リスクマネジメント (Risk Management)', '', 'The systematic process of identifying, assessing, and mitigating risks to an organization.', 'リスクを特定し評価し対策する管理プロセス (リスクマネジメント)', 'Used in projects, finance, cybersecurity, and daily operations.', ', Cybersecurity: buy insurance, install firewall, train staff , Project: identify delay risks, add buffer time , Finance: diversify investments', 'Identify, assess, control risks.', 'リスクを洗い出し対策する管理', false),,
  (116, 4, 'リバースエンジニアリング (Reverse Engineering)', '', 'The process of taking apart a product to understand its design, components, or code, often to recreate or analyze it.', '完成品を分解・解析して仕組みを理解する技術 (リバースエンジニアリング)', 'Used for malware analysis, legacy system recovery, and compatibility research.', ', Analyzing competitor''s product to learn how it works , Malware researcher disassembling virus code , Recovering lost source code from executable', 'Take it apart to figure how it was made.', '製品を解析して仕組みを解明', false),,
  (117, 4, 'レスポンスタイム (Response Time)', '', 'The time between a user''s request and the system''s first response or completion of that request.', 'ユーザーの操作に対してシステムが反応するまでの時間 (レスポンスタイム)', 'Used to measure system performance and user experience.', ', Website loading after click , Search engine returning results , App opening from tap to display', 'Request → response duration.', '操作から反応までの時間', false),,
  (118, 4, 'ロールバック (Rollback)', '', 'The process of reverting a system or database to a previous, consistent state after a failed transaction or error.', '失敗した処理を取り消し、前の状態に戻す処理 (ロールバック)', 'Used in database transactions, software updates, and version control.', ', Cancel online payment if credit card fails , Revert to older OS after bad update fails , Undo git push in GitHub', 'Undo changes to go back to safe point.', '直前の正しい状態まで戻す', false),,
  (119, 4, 'ロールフォワード (Roll-forward)', '', 'The process of applying saved changes (logs) to a backup to bring a system to the most recent state after a failure.', 'バックアップに変更履歴を適用して最新状態に戻す復旧処理 (ロールフォワード)', 'Used in database recovery after a system crash.', ', Restoring database from morning backup then applying today''s transaction log , After power outage, applying recent changes to server , Recovery from transaction log', 'Bring backup forward to current time with logs.', 'ログを適用して最新状態に復元', false),,
  (120, 4, 'ロングテール (Long Tail)', '', 'A business strategy where selling many low-demand niche products generates as much or more profit than selling a few bestsellers.', '売れ筋ではない多数の商品の総和が、ベストセラーと同じかそれ以上の売上になる戦略 (ロングテール)', 'Used by e-commerce and streaming services to profit from vast inventory of less popular items.', ', Amazon selling millions of obscure books , Netflix library of old and niche movies , Spotify''s deep catalog of indie music', 'Niche products in small quantities add up to big money.', 'ニッチ商品の集積が生む利益', false),;