-- IT Passport Vocabulary Seed Data
-- Generated from deepseek_csv_20260507_17bc21.txt
-- Total: 179 words across 6 pages

INSERT INTO words (id, page_num, word, full_name, overview_en, overview_jp, usage, examples, quick_memory_en, quick_memory_jp, studied)
VALUES
  (121, 5, 'BOT (Bot)', '', 'An automated software program that performs repetitive tasks over a network or on a device.', '自動で反復作業を行うプログラム (ボット)', 'Used for both good (search engines, customer service) and bad (spam, attacks).', ', Googlebot crawling websites , Chatbot answering customer questions , Twitter bot posting automated weather updates', 'Robot software that works automatically.', '自動動作するソフトウェア', false),,
  (122, 5, 'DoS攻撃 (DoS Attack)', '', 'A cyberattack that overwhelms a server with fake traffic or requests, making it unavailable to real users.', 'サーバに大量のリクエストを送り機能停止させる攻撃 (ディーオーエスこうげき)', 'Used by hackers to shut down websites, online games, or services.', ', Flooding a bank website so no one can log in , Online game server becoming unplayable , Crashing a school''s registration system on enrollment day', 'Crash service with fake traffic flood.', '偽の通信でサービスを止める', false),,
  (123, 5, 'IPスプーフィング (IP Spoofing)', '', 'A technique where an attacker alters packet headers to disguise their real IP address, pretending to be a trusted source.', '送信元IPアドレスを偽装する攻撃技術 (アイピースプーフィング)', 'Used in DDoS attacks, bypassing IP filters, and hiding identity.', ', Hacker making attack look like it comes from internal company network , Pretending to be a trusted partner server , Hiding location during a cyberattack', 'Fake return address on internet packages.', 'IPアドレスを詐称する技術', false),,
  (124, 5, 'SQLインジェクション (SQL Injection)', '', 'An attack where malicious SQL code is inserted into a web form input to manipulate or steal database data.', 'Web入力フォームに悪意のあるSQLコードを挿入する攻撃 (SQLインジェクション)', 'Used to bypass login, steal customer data, or delete database tables.', ', Entering '' OR ''1''=''1 as password to bypass login , Stealing credit card numbers from e-commerce site , Deleting a database table via vulnerable search box', 'Trick database by typing code into a form.', '入力欄にSQLを忍び込ませる攻撃', false),,
  (125, 5, 'ガンブラー (Gumblar)', '', 'A type of malware that steals FTP credentials and injects malicious JavaScript into web pages, infecting site visitors.', 'FTP情報を盗み、Webページに悪意のあるJavaScriptを挿入するマルウェア (ガンブラー)', 'Used to spread malware by compromising legitimate websites.', ', Infected website showing fake codec update , Injected script redirecting visitors to exploit kit , Website defacement via stolen credentials', 'Malware that turns websites into infection sources.', 'Webサイトを感染源に変えるマルウェア', false),,
  (126, 5, 'キーロガー (Keylogger)', '', 'A type of malware that records every keystroke a user makes, capturing passwords, messages, and sensitive data.', 'キーボードの入力を全て記録するマルウェア (キーロガー)', 'Used by attackers to steal passwords, credit card numbers, and personal messages.', ', Recording typed passwords on a public computer , Capturing credit card number during online shopping , Logging chat messages for corporate espionage', 'Digital eavesdropper on your keyboard.', 'キーボード入力記録ソフト', false),,
  (127, 5, 'クッキー (Cookie)', '', 'A small text file stored by a website on a user''s browser to remember stateful information like login status or preferences.', 'Webサイトがブラウザに保存する小さなテキストファイル (クッキー)', 'Used for authentication, shopping cart contents, language preferences, and tracking.', ', Staying logged into Gmail across visits , Amazon cart keeping items after closing browser , Website remembering dark mode preference', 'Website memory on your computer.', 'Webサイトの状態保存データ', false),,
  (128, 5, 'クラッキング (Cracking)', '', 'Unauthorized breaking into computer systems or software, often with malicious intent (different from ethical hacking).', '悪意を持ってコンピュータシステムやソフトウェアに侵入・破壊行為をすること (クラッキング)', 'Used for data theft, vandalism, software piracy, or financial gain.', ', Removing software license check illegally , Breaking into a bank database to steal money , Defacing government websites', 'Malicious hacking for bad purposes.', '悪意のあるハッキング行為', false),,
  (129, 5, 'クロスサイトスクリプティング (Cross-site Scripting / XSS)', '', 'An attack where malicious scripts are injected into trusted websites, then executed in victims'' browsers.', '悪意のあるスクリプトをWebサイトに埋め込み、閲覧者のブラウザで実行させる攻撃 (クロスサイトスクリプティング)', 'Used to steal cookies, session tokens, or redirect users to malicious sites.', ', Posting a comment with JavaScript that steals login cookies , Fake login form injected into banking page , Redirecting users to phishing site after clicking legitimate link', 'Evil code running inside trusted website.', 'Webサイトに悪意のコードを埋め込む', false),,
  (130, 5, 'サラミ法 (Salami Slicing / Salami Technique)', '', 'A fraud technique where small, unnoticeable amounts of money are stolen from many transactions over time.', '一回あたりは少額の金銭を多くの取引から少しずつ盗む手口 (サラミほう)', 'Used in financial fraud and computer crime.', ', Rounding down interest calculations and stealing fractions of cents , Stealing 1 yen from millions of transactions , Skimming tiny amounts from ETF trades', 'Steal tiny slices that add up to a feast.', '少額をこっそり何度も盗む手口', false),,
  (131, 5, '辞書攻撃 (Dictionary Attack)', '', 'A password cracking method that tries a list of common words and passwords (a dictionary) against a login system.', 'よく使われる単語やパスワードのリストを総当たりで試す攻撃方法 (じしょこうげき)', 'Used by attackers to break weak passwords quickly.', ', Trying password123, admin, letmein against accounts , Testing common birthdays like 1990, 1111, 123456 , Using leaked password databases for credential stuffing', 'Try every word in the book as password.', '辞書の単語をパスワードに試す', false),,
  (132, 5, 'スパイウェア (Spyware)', '', 'Malware that secretly monitors user activities and sends collected information (browsing habits, keystrokes, data) to a third party.', 'ユーザーの行動を秘密裏に監視し情報を収集するマルウェア (スパイウェア)', 'Used for targeted advertising, identity theft, or corporate espionage.', ', Browser extensions tracking all visited websites , Fake download managers collecting browsing history , Software secretly recording screenshots', 'Software that spies on you.', '秘密に情報を収集するソフト', false),,
  (133, 5, 'スパムメール (Spam Mail)', '', 'Unsolicited, bulk emails sent indiscriminately to many recipients, often for advertising or phishing.', '受信者の同意なく大量に送りつけられる迷惑メール (スパムメール)', 'Used by advertisers, scammers, and malware distributors.', ', Nigerian prince inheritance scam emails , Fake lottery winning notifications , Mass emails advertising fake Viagra', 'Junk mail in your inbox.', '大量に送られる迷惑メール', false),,
  (134, 5, 'セキュリティホール (Security Hole / Vulnerability)', '', 'A weakness or flaw in system design, implementation, or configuration that can be exploited by attackers.', 'システムの設計や実装上の欠陥で、攻撃に悪用される可能性がある弱点 (セキュリティホール)', 'Existed in all software; needs patching with updates.', ', Heartbleed bug in OpenSSL , Microsoft Windows zero-day vulnerability , Default admin password never changed on router', 'Crack in the digital armor.', 'セキュリティ上の欠陥や弱点', false),,
  (135, 5, 'ゼロデイ攻撃 (Zero-day Attack)', '', 'An attack that exploits a previously unknown vulnerability before the software developer has released a patch.', 'セキュリティホールが公開される前にその脆弱性を悪用する攻撃 (ゼロデイこうげき)', 'Used by advanced attackers and nation-states for high-value targets.', ', Attacking Windows before Microsoft knows about bug , Exploiting unknown Chrome vulnerability , Stuxnet using four zero-days against Iran', 'Attack on unknown, unfixed holes.', '修正前に突かれる脆弱性攻撃', false),,
  (136, 5, 'ソーシャルエンジニアリング (Social Engineering)', '', 'Psychological manipulation of people into revealing confidential information or performing actions.', '人間の心理的弱点をついて情報を引き出したり行動させる手口 (ソーシャルエンジニアリング)', 'Used to bypass technical security by tricking people.', ', Calling helpdesk pretending to be CEO to reset password , Fake IT person asking for employee login , USB drives lost in parking lot containing malware', 'Hacking humans, not computers.', '人の心理を操作する情報詐取', false),,
  (137, 5, 'ドライブバイダウンロード (Drive-by Download)', '', 'An unintentional download of malware that happens when a user visits a compromised or malicious website, without clicking anything.', '悪意のあるWebサイトを閲覧しただけで自動的にマルウェアがダウンロードされる仕組み (ドライブバイダウンロード)', 'Used to infect victims just by visiting a website (no click required).', ', Visiting a hacked news site, malware downloads silently , Malicious ad on legitimate site triggering download , Compromised WordPress plugin infecting visitors', 'Get infected just by visiting a website.', 'サイト閲覧だけで感染する', false),,
  (138, 5, 'トロイの木馬 (Trojan Horse)', '', 'Malware disguised as legitimate software, tricking users into installing it, then performing harmful actions.', '正規のソフトウェアを装ってユーザーにインストールさせるマルウェア (トロイのきぼく)', 'Used for backdoor access, data theft, or dropping more malware.', ', Fake Flash Player Update that installs ransomware , Cracked game download containing keylogger , Free PDF converter that steals browser passwords', 'Evil hiding inside something good.', '正規ソフトに偽装した悪意ソフト', false),,
  (139, 5, 'パスワードクラック (Password Crack)', '', 'The process of recovering passwords from stored data or by guessing using various attack methods.', 'パスワードを解析・推測して破る行為 (パスワードクラック)', 'Used by attackers or security testers to gain unauthorized access.', ', Cracking hashed passwords from leaked database , Guessing princess123 from common password list , Using rainbow tables to reverse hash', 'Breaking passwords using math and guessing.', 'パスワードを突破する行為', false),,
  (140, 5, 'パスワードリスト攻撃 (Password List Attack / Credential Stuffing)', '', 'An attack that uses previously leaked username-password pairs from one site to try to log into other sites.', '他のサービスから漏れたID・パスワードのリストを使って別のサービスにログインを試みる攻撃 (パスワードリストこうげき)', 'Used because people reuse same password on multiple sites.', ', LinkedIn leak used to hack into Gmail accounts , Breached password from old forum used to access bank account , Trying same email/password combo on 10 popular websites', 'Try leaked passwords on other sites.', 'リスト流用のログイン試行攻撃', false),,
  (141, 5, 'バックドア (Backdoor)', '', 'A secret method of bypassing normal authentication to gain unauthorized access to a system.', '正規の認証をバイパスしてシステムにアクセスする秘密の入口 (バックドア)', 'Left by developers for maintenance or installed by malware for persistence.', ', Undocumented admin account in router firmware , Malware opening a hidden port for remote control , Developer leaving debug=1 parameter to bypass login', 'Secret entrance to bypass the front door.', '正規ルート外の秘密入口', false),,
  (142, 5, 'バッファオーバーフロー攻撃 (Buffer Overflow Attack)', '', 'An attack that writes data beyond a buffer''s allocated memory, corrupting adjacent data and potentially executing malicious code.', 'メモリ領域を超えてデータを書き込み、プログラムを制御する攻撃 (バッファオーバーフローこうげき)', 'Used to crash systems or inject/execute attacker code.', ', Sending more data than expected to crash a server , Overwriting function return address to run malware , Exploiting strcpy() without bounds checking', 'Overflow a cup, spill into dangerous places.', 'メモリ領域からあふれ出る攻撃', false),,
  (143, 5, 'フィッシング詐欺 (Phishing Scam)', '', 'A fraud attempt where attackers impersonate legitimate organizations via email, text, or fake websites to trick victims into revealing sensitive info.', '実在の企業を装って個人情報を詐取する手口 (フィッシングさぎ)', 'Used to steal login credentials, credit cards, and personal data.', ', Email pretending to be your bank asking to verify account , Fake login page that looks exactly like Amazon , Text message claiming package delivery needs payment', 'Fake bait to steal your login.', '偽サイトで情報を盗む詐欺', false),,
  (144, 5, 'ブルートフォース攻撃 (Brute-force Attack)', '', 'An attack that tries every possible combination of characters (from a to zzzzzz) until the correct password is found.', '考えられる全ての文字列を総当たりで試す攻撃 (ブルートフォースこうげき)', 'Used when dictionary attacks fail, but very time-consuming for strong passwords.', ', Trying aaaaaa, aaaaab, aaaaac... for password cracking , Cracking 4-digit PIN from 0000 to 9999 (10,000 tries) , Server login attempts from a script', 'Try every key until one opens the lock.', '全ての組合せを力ずくで試す', false),,
  (145, 5, 'ポートスキャン (Port Scan)', '', 'A technique to probe a server for open ports (communication endpoints) to discover what services are running.', 'サーバのどの通信ポートが開いているかを調べる調査行為 (ポートスキャン)', 'Used by both administrators (to check security) and attackers (to find attack surfaces).', ', Nmap scanning company network for open SSH (port 22) , Checking if web server port 80 and 443 are open , Probing for open database ports (3306 MySQL)', 'Knock on every door to see which open.', '開いている通信口を探す', false),,
  (146, 5, 'マルウェア (Malware)', '', 'Malicious software designed to harm, exploit, or otherwise compromise a computer system (includes viruses, worms, trojans, ransomware).', '悪意のあるソフトウェアの総称 (マルウェア)', 'Used for data theft, extortion, espionage, or system destruction.', ', Ransomware encrypting files and demanding Bitcoin , Spyware stealing passwords , Worm spreading across corporate network', 'Bad software = malware.', '悪意あるソフトの総称', false),,
  (147, 5, '水飲み場攻撃 (Watering Hole Attack)', '', 'A targeted attack where attackers infect a website that the victim group is known to visit frequently.', '標的グループがよく訪れるWebサイトを経由して感染させる攻撃 (みずのみばこうげき)', 'Used to compromise specific organizations by infecting their trusted external sites.', ', Hacking a financial industry news site to infect bank employees , Compromising a medical journal to attack hospital workers , Poisoning a government contractor''s favorite forum', 'Poison the water hole the target drinks from.', '標的のよく行くサイトを狙う', false),,
  (148, 5, 'メール爆弾 (Email Bomb)', '', 'An attack that sends an overwhelming volume of emails to a target address or server to cause disruption.', '大量のメールを送りつけてメールサーバや受信者を機能不全に陥れる攻撃 (メールばくだん)', 'Used for denial of service, harassment, or distraction.', ', Thousands of confirmation emails flooding inbox , Reply-all storm after mass email , Server crashing from 100,000 emails/minute', 'Explode inbox with thousands of emails.', '大量メールで受信者を攻撃', false),,
  (149, 5, 'ランサムウェア (Ransomware)', '', 'Malware that encrypts a victim''s files and demands payment (ransom) for the decryption key.', 'ファイルを暗号化し復号と引き換えに身代金を要求するマルウェア (ランサムウェア)', 'Used for extortion, often demanding Bitcoin or other cryptocurrency.', ', WannaCry attack on hospitals (2017) , Colonial Pipeline paying $4.4 million ransom , Police department losing all bodycam footage', 'Your files locked, pay to unlock.', 'データを人質に身代金要求', false),,
  (150, 5, 'ワーム (Worm)', '', 'Self-replicating malware that spreads across networks without needing user interaction or attaching to a host file.', 'ネットワークを通じて自己増殖するマルウェア (ワーム)', 'Used to rapidly infect many systems, often for botnets or sabotage.', ', Conficker worm infecting millions of Windows PCs , Morris worm (1988) early internet attack , SQL Slammer crashing servers in 10 minutes', 'Spreads itself like a digital disease.', '自分で増殖して広がるウイルス', false),;