-- IT Passport Vocabulary Seed Data
-- Generated from deepseek_csv_20260507_17bc21.txt
-- Total: 179 words across 6 pages

INSERT INTO words (id, page_num, word, full_name, overview_en, overview_jp, usage, examples, quick_memory_en, quick_memory_jp, studied)
VALUES
  (31, 2, 'IrDA (Infrared Data Association)', '', 'A standard for wireless data transfer using infrared light, requiring line of sight.', '赤外線を使った近距離無線通信規格 (インフラレッド)', 'Used for short-range communication between devices like old phones, laptops, and printers.', ', Beaming contacts between old phones , Printing from PDA to printer , Wireless file transfer on legacy laptops', 'Line-of-sight infrared wireless.', '赤外線の通信規格', false),,
  (32, 2, 'ISMS (Information Security Management System)', '', 'A systematic approach to managing sensitive company information and ensuring security.', '情報セキュリティを管理する仕組み (アイエスエムエス)', 'Used to establish security policies, procedures, and controls, often certified under ISO 27001.', ', Company-wide security policy implementation , Risk assessment for data breaches , ISO 27001 certification process', 'System for info security management.', 'セキュリティ管理の仕組み', false),,
  (33, 2, 'ISO (International Organization for Standardization)', '', 'An international body that develops and publishes standards for various industries.', '国際標準化機構 (こくさいひょうじゅんかきこう)', 'Used to certify products and management systems for quality, safety, and efficiency.', ', ISO 9001 for quality management , ISO 27001 for security , ISO 14001 for environment', 'Global standards organization.', '国際規格を決める組織', false),,
  (34, 2, 'ISO14000', '', 'A family of standards for environmental management systems.', '環境マネジメントに関する国際規格群 (ISO14000)', 'Used by organizations to reduce environmental impact and comply with regulations.', ', Factory waste reduction certification , Company carbon footprint measurement , Environmental compliance audit', 'Environmental management standards.', '環境管理の国際規格', false),,
  (35, 2, 'ISO27000', '', 'A family of standards for information security management systems (ISMS).', '情報セキュリティ管理の国際規格群 (ISO27000)', 'Used to certify that an organization has proper security controls in place.', ', Data center security certification , Cloud service provider compliance , Bank information security audit', 'Information security standards family.', 'セキュリティ管理の規格群', false),,
  (36, 2, 'ISO9000', '', 'A family of standards for quality management systems.', '品質マネジメントの国際規格群 (ISO9000)', 'Used to ensure consistent product and service quality across organizations.', ', Manufacturing quality control certification , Hospital patient care standards , Airline service quality management', 'Quality management standards.', '品質管理の国際規格', false),,
  (37, 2, 'ITIL (Information Technology Infrastructure Library)', '', 'A framework of best practices for IT service management (ITSM).', 'ITサービス管理のベストプラクティス集 (アイティル)', 'Used by IT departments to align IT services with business needs, handle incidents, and manage changes.', ', Setting up a service desk , Managing IT changes without downtime , Incident response workflow design', 'Best practices for IT service.', 'IT運用のベストプラクティス', false),,
  (38, 2, 'ITガバナンス (IT Governance)', '', 'A framework for ensuring IT investments support business goals and manage risks.', 'ITを戦略的に統制する仕組み (ITガバナンス)', 'Used by boards and executives to align IT with strategy, measure performance, and comply with regulations.', ', IT steering committee approving projects , Cybersecurity risk reporting to board , IT budget and ROI tracking', 'Control system for company IT.', 'ITの会社統治', false),,
  (39, 2, 'KJ法 (KJ Method)', '', 'A creative brainstorming technique where ideas are written on cards, grouped, and organized.', 'カードに書いた情報を整理して新しい考えを生む方法 (KJほう)', 'Used in planning, problem-solving, and research to make sense of complex information.', ', New product brainstorm workshop , Customer feedback organization , Strategic planning sessions', 'Card sorting for idea organization.', 'カードで情報を整理', false),,
  (40, 2, 'M＆A (Mergers and Acquisitions)', '', 'The process of companies combining (merger) or one buying another (acquisition).', '企業の合併と買収 (エムアンドエイ)', 'Used to grow market share, enter new markets, acquire technology, or eliminate competition.', ', Disney buying Pixar , Microsoft acquiring Activision Blizzard , Two banks merging into one', 'Companies joining or buying each other.', '企業の合併・買収', false),,
  (41, 2, 'MACアドレス (MAC Address)', '', 'A unique hardware identifier assigned to network interfaces like Wi-Fi or Ethernet cards.', 'ネットワーク機器に固有の製造番号 (マックアドレス)', 'Used to identify devices on a local network and for MAC filtering in Wi-Fi security.', ', Router assigning fixed IP by MAC , MAC address whitelisting for office Wi-Fi , Device tracking in network management', 'Hardware serial number for network.', 'ネットワーク機器の個体番号', false),,
  (42, 2, 'MBO (Management by Objectives)', '', 'A management system where managers and employees set shared goals together.', '目標による管理 (もくひょうによるかんり)', 'Used to align individual performance with company objectives through regular goal reviews.', ', Setting quarterly OKRs with team , Annual performance review by goal completion , Sales team revenue targets', 'Manage by shared goal setting.', '目標を決めて管理する手法', false),,
  (43, 2, 'MP3', '', 'A digital audio coding format that compresses sound without significant quality loss.', '音声を圧縮するデジタル形式 (エムピースリー)', 'Used for music streaming, storage, and sharing across devices and platforms.', ', Spotify streaming in MP3 , iPhone music library , Podcast audio files', 'Compressed music file format.', '音楽圧縮の標準形式', false),,
  (44, 2, 'MRP (Material Requirements Planning)', '', 'A system for calculating raw material needs based on production schedules and inventory.', '生産計画に基づいて資材を計算するシステム (エムアールピー)', 'Used in manufacturing to ensure materials are available for production and minimize inventory costs.', ', Car factory ordering parts just in time , Electronics assembly line planning , Food production ingredient ordering', 'Calculate what materials to buy and when.', '資材所要量の計画', false),,
  (45, 2, 'MTBF (Mean Time Between Failures)', '', 'The average time between failures of a repairable system or component.', '平均故障間隔 (へいきんこしょうかんかく)', 'Used to measure reliability and predict how often a device will fail.', ', Hard drive reliability rating (e.g., 1M hours) , Car engine durability comparison , Industrial machine maintenance scheduling', 'Average time between breakdowns.', '故障から次の故障までの時間', false),,
  (46, 2, 'MTTR (Mean Time To Repair)', '', 'The average time needed to repair a failed system or component.', '平均修復時間 (へいきんしゅうふくじかん)', 'Used to measure maintainability and estimate how long systems will be down after failure.', ', Server repair time target (e.g., 4 hours) , Elevator breakdown recovery SLA , Factory machine maintenance response', 'Average time to fix after failure.', '修理にかかる平均時間', false),,
  (47, 2, 'NDA (Non-Disclosure Agreement)', '', 'A legal contract that protects confidential information from being shared.', '秘密保持契約 (ひみつほじけいやく)', 'Used before sharing business secrets, customer data, or intellectual property with partners or employees.', ', Employee signing at hire , Partner discussing a new product , Consultant accessing financial data', 'Legal promise to keep secrets.', '秘密を守る契約書', false),,
  (48, 2, 'OEM (Original Equipment Manufacturer)', '', 'A company that makes parts or products that another company sells under its own brand.', '他社ブランドで販売する製品を製造する会社 (オーイーエム)', 'Used to produce goods without building factories, letting brands focus on marketing and sales.', ', Foxconn making iPhones for Apple , Samsung making screens for other brands , Generic laptops sold as store brands', 'Make product for another''s brand.', '他社ブランドで生産', false),,
  (49, 2, 'Off-JT (Off-the-Job Training)', '', 'Training that takes place away from the regular work environment, like classrooms or workshops.', '職場を離れて行う研修 (オフザジョブトレーニング)', 'Used to teach theoretical knowledge, soft skills, or certifications without work distractions.', ', Leadership workshop offsite , Programming bootcamp course , Safety certification class', 'Training outside the workplace.', '職場外での研修', false),,
  (50, 2, 'OJT (On-the-Job Training)', '', 'Training that takes place at the actual workplace while performing real tasks.', '職場で実際の仕事をしながら行う研修 (オンジョブトレーニング)', 'Used to learn practical skills directly applicable to daily work with supervisor guidance.', ', New cashier learning register with mentor , Junior developer fixing real bugs , Apprentice learning from senior chef', 'Learning while working.', '実務を通じた研修', false),,
  (51, 2, 'OSS (Open Source Software)', '', 'Software with source code freely available for use, modification, and distribution.', 'ソースコードが公開されているソフトウェア (オープンソースソフトウェア)', 'Used by developers to build applications without starting from scratch, saving time and cost.', ', Linux operating system , Apache web server , LibreOffice productivity suite', 'Free software with visible code.', 'ソースコードが開かれたソフト', false),,
  (52, 2, 'PDCAサイクル (PDCA Cycle)', '', 'A continuous improvement cycle: Plan, Do, Check, Act.', '計画・実行・評価・改善を繰り返す手法 (ピーディーシーエーサイクル)', 'Used in quality management, project management, and personal productivity.', ', Manufacturing quality control , Marketing campaign optimization , Personal habit improvement', 'Plan → Do → Check → Act loop.', '計画・実行・評価・改善の繰り返し', false),,
  (53, 2, 'PDF (Portable Document Format)', '', 'A file format that preserves document layout and fonts across all devices.', 'レイアウトが変わらない電子文書形式 (ピーディーエフ)', 'Used for sharing documents that need exact formatting, like contracts, invoices, and ebooks.', ', Sending a resume as PDF , Ebook distribution , Bank statement archiving', 'Fixed-layout document format.', 'レイアウト固定の文書形式', false),,
  (54, 2, 'PKI (Public Key Infrastructure)', '', 'A system for managing digital certificates and encryption keys for secure communication.', '公開鍵暗号のための基盤システム (ピーケーアイ)', 'Used to enable HTTPS, email encryption, and digital signatures across the internet.', ', SSL/TLS certificates for websites , Government digital ID cards , Company VPN authentication', 'System for digital keys and certificates.', '電子証明書の運用基盤', false),,
  (55, 2, 'PLC (Product Life Cycle)', '', 'The stages a product goes through: Introduction, Growth, Maturity, Decline.', '製品の市場での生涯サイクル (プロダクト・ライフ・サイクル)', 'Used to plan marketing strategy, pricing, and product updates based on lifecycle stage.', ', iPhone: growth to maturity , Fax machines: decline stage , New EV: introduction stage', 'Stages: intro → growth → mature → decline.', '製品の寿命サイクル', false),,
  (56, 2, 'PL法 (Product Liability Act)', '', 'A law that holds manufacturers responsible for injuries caused by defective products.', '製品の欠陥で被害が出た場合に製造業者の責任を問う法律 (プロダクト・ライアビリティほう)', 'Used by consumers to sue for damages from defective cars, appliances, food, or medicine.', ', Airbag defect recall lawsuit , Food poisoning from contaminated product , Toy choking hazard claim', 'Manufacturer pays for product defects.', '製品欠陥の製造者責任', false),,
  (57, 2, 'PMBOK (Project Management Body of Knowledge)', '', 'A guide covering standard terminology and best practices in project management.', 'プロジェクトマネジメントの知識体系 (ピーボック)', 'Used by project managers to follow standard processes across industries like IT, construction, and events.', ', PMP certification exam preparation , Software project planning , Construction project scheduling', 'Project management standard guide.', 'プロジェクト管理の標準知識', false),,
  (58, 2, 'POSシステム (POS System)', '', 'A system that records sales transactions at checkout and updates inventory in real-time.', '販売時点情報管理システム (ポスシステム / はんばいじてんてんじょうほう)', 'Used in retail stores, restaurants, and hotels to process payments and track sales data.', ', 711 cash register tracking inventory , Restaurant tablet ordering system , Self-checkout at supermarket', 'Register that tracks sales and stock.', 'レジ＋在庫管理システム', false),,
  (59, 2, 'PPM (Product Portfolio Management)', '', 'A method to manage a company''s products based on market growth and market share (BCG matrix).', '製品ポートフォリオ管理 (プロダクト・ポートフォリオ・マネジメント)', 'Used to decide which products to invest in, maintain, or phase out.', ', BCG matrix: Stars, Cash Cows, Question Marks, Dogs , Car company deciding to kill a slow-selling model , Tech firm funding new flagship product', 'Manage products like an investment portfolio.', '製品を投資で管理する手法', false),,
  (60, 2, 'RAIDシステム (RAID System)', '', 'A technology that combines multiple hard drives together for performance, redundancy, or both.', '複数のディスクをまとめて使う技術 (レイドシステム)', 'Used in servers and storage systems to prevent data loss from a single disk failure.', ', RAID 1: mirroring for safety , RAID 5: striping with parity , Server with 4 drives in RAID 10', 'Multiple disks acting as one for safety or speed.', '複数ディスクを統合する技術', false),;