-- IT Passport Vocabulary Seed Data
-- Generated from deepseek_csv_20260507_17bc21.txt
-- Total: 179 words across 6 pages

INSERT INTO words (id, page_num, word, full_name, overview_en, overview_jp, usage, examples, quick_memory_en, quick_memory_jp, studied)
VALUES
  (151, 5, 'セッションハイジャック (Session Hijacking)', '', 'An attack where an attacker steals a user''s session ID (after login) to take over their authenticated session.', 'ログイン後のセッションIDを盗み、ユーザーの認証状態を乗っ取る攻撃 (セッションハイジャック)', 'Used to bypass login and impersonate a user without needing their password.', ', Stealing cookie from public Wi-Fi to access someone''s Facebook , Capturing session token via XSS attack , Man-in-the-middle intercepting session ID', 'Steal your already-open door key.', 'ログイン後の状態を奪う攻撃', false),,
  (152, 5, 'DNSキャッシュポイズニング (DNS Cache Poisoning)', '', 'An attack that corrupts a DNS server''s cache to redirect users from legitimate websites to malicious ones.', 'DNSサーバのキャッシュを改ざんし、正規サイトへのアクセスを偽サイトに誘導する攻撃 (DNSキャッシュポイズニング)', 'Used to send victims to fake banking sites or malware downloads without their knowledge.', ', Typing google.com but being sent to fake page , Bank URL resolving to attacker''s phishing server , ISP DNS returning wrong IP for a website', 'Poison the internet''s phone book.', 'DNSの住所録を書き換える', false),,
  (153, 5, 'ディレクトリトラバーサル (Directory Traversal / Path Traversal)', '', 'An attack that manipulates file paths to access files and directories stored outside the web root folder.', 'ファイルパスを操作してWebルート外の重要なファイルにアクセスする攻撃 (ディレクトリトラバーサル)', 'Used to read sensitive files like passwords, configs, or source code.', ', ../../../../etc/passwd to read Unix password file , Accessing application configuration file with passwords , Reading Windows boot.ini via URL manipulation', 'Climb out of the web folder to steal files.', 'フォルダ階層をさかのぼる攻撃', false),,
  (154, 5, 'クリックジャッキング (Clickjacking)', '', 'A technique where a malicious site hides a transparent button or iframe over a legitimate button to trick users into clicking something they don''t see.', '透明なボタンを装飾し、ユーザーに気付かず別の操作をさせる攻撃 (クリックジャッキング)', 'Used to trick users into enabling camera, liking a page, or transferring money unknowingly.', ', Invisible Enable Camera button disguised as Play Video , Hidden like button stealing social media interactions , Fake Claim Prize that actually transfers Bitcoin', 'You click what you don''t see.', '見えないものをクリックさせる', false),,
  (155, 6, 'APOP (Authenticated Post Office Protocol)', '', 'An extension of POP3 that uses MD5 hashing to send passwords encrypted rather than in plain text.', 'POP3に認証機能を追加したプロトコル (エーポップ)', 'Used in legacy email systems to retrieve email from servers with better password security.', ', Old email clients connecting to ISP mail servers , Retrieving email from on-premise legacy mail server , Secure POP email before widespread IMAP use', 'POP3 with password encryption.', '暗号化パスワードのPOP', false),,
  (156, 6, 'ARP (Address Resolution Protocol)', '', 'A protocol that maps an IP address to a physical MAC address on a local network.', 'IPアドレスからMACアドレスを調べるプロトコル (エーアールピー)', 'Used by devices to find each other on the same local network (Ethernet/Wi-Fi).', ', Computer asking Who has 192.168.1.1? to find router , Switch learning which port has which MAC , ARP table showing IP-MAC pairs', 'Find hardware address from IP address.', 'IP→MACを変換する仕組み', false),,
  (157, 6, 'DHCP (Dynamic Host Configuration Protocol)', '', 'A protocol that automatically assigns IP addresses and network settings to devices on a network.', 'ネットワーク機器に自動でIPアドレスを割り当てるプロトコル (ディーエイチシーピー)', 'Used to avoid manually configuring IP on every device (laptops, phones, printers).', ', Home router giving 192.168.1.x to your phone and laptop , Office network assigning IP to new employee''s computer , Hotel Wi-Fi providing IP upon connection', 'Automatic IP address dispenser.', 'IPアドレス自動割り当て', false),,
  (158, 6, 'DNS (Domain Name System)', '', 'The internet''s phone book that translates human-friendly domain names (google.com) into IP addresses (142.250.190.46).', 'ドメイン名とIPアドレスを変換する仕組み (ディーエヌエス)', 'Used every time you type a website name into a browser.', ', google.com → 142.250.190.46 , Typing amazon.com without remembering IP numbers , Email routing via MX records', 'Translates names to numbers on internet.', '名前→数字を変換する仕組み', false),,
  (159, 6, 'ESSID (Extended Service Set Identifier)', '', 'The name of a Wi-Fi network that users see and select when connecting.', '無線LANのネットワーク名 (ESSID / エッシド)', 'Used to identify and connect to a specific wireless network among many.', ', Selecting Starbucks Wi-Fi from your phone , Home network named MyHome2.4G , Office network Corp_WiFi visible to employees', 'Your Wi-Fi network''s name.', 'Wi-Fiネットワークの名前', false),,
  (160, 6, 'FTP (File Transfer Protocol)', '', 'A standard network protocol for transferring files between a client and server on a computer network.', 'ファイル転送のための標準プロトコル (エフティーピー)', 'Used to upload website files to a hosting server or download large files.', ', Uploading HTML files to web hosting server , Downloading Linux ISO images from mirrors , WordPress plugin installation via FTP', 'Move files between computers.', 'ファイル転送の標準手順', false),,
  (161, 6, 'HTTP (HyperText Transfer Protocol)', '', 'The foundation protocol for data communication on the World Wide Web, used for loading web pages.', 'Webページを表示するための通信プロトコル (エイチティーティーピー)', 'Used by browsers to request and receive web pages, images, and videos.', ', Typing http://example.com in browser (unsecured) , Browser sending GET request for index.html , Communication between frontend and backend', 'Web page delivery protocol (not secure).', 'Webの基本通信ルール', false),,
  (162, 6, 'HTTPS (HyperText Transfer Protocol Secure)', '', 'The secure version of HTTP using SSL/TLS encryption to protect data between browser and website.', 'HTTPに暗号化機能を追加した安全なプロトコル (エイチティーティーピーエス)', 'Used for banking, shopping, login pages, and any site handling sensitive data.', ', Banking website with padlock icon in address bar , Gmail login over HTTPS , Amazon checkout page', 'Secure web communication with lock.', '暗号化されたWeb通信', false),,
  (163, 6, 'ICMP (Internet Control Message Protocol)', '', 'A protocol used for error reporting and diagnostic functions like ping and traceroute.', 'ネットワークの診断やエラー通知に使うプロトコル (アイシーエムピー)', 'Used by network administrators to test connectivity and troubleshoot.', ', ping google.com to check if internet works , traceroute to see path packets take , Destination Unreachable error messages', 'Internet''s diagnostic and error reporting tool.', '通信状態確認の仕組み', false),,
  (164, 6, 'IMAP (Internet Message Access Protocol)', '', 'An email protocol that stores messages on the server and synchronizes across multiple devices.', 'メールをサーバ上で管理し複数端末で同期するプロトコル (アイマップ)', 'Used by email clients (Outlook, Gmail app, Thunderbird) to access mail.', ', Reading same email on phone, laptop, tablet with all showing read , Folder structure (Inbox, Sent) synced across devices , Gmail using IMAP for third-party clients', 'Email stays on server, syncs everywhere.', 'サーバでメールを同期する', false),,
  (165, 6, 'IP (Internet Protocol)', '', 'The principal protocol for addressing and routing packets of data across networks to their destination.', 'データを宛先まで届けるためのインターネットの基幹プロトコル (アイピー)', 'Used in every internet communication to provide addressing and packet forwarding.', ', Sending data from Tokyo to New York server , IP header containing source and destination addresses , Routing packet through multiple routers', 'Internet''s postal service for data.', 'データを届ける基本ルール', false),,
  (166, 6, 'MIME (Multipurpose Internet Mail Extensions)', '', 'An extension to email that allows sending non-text attachments like images, audio, and video.', 'メールでテキスト以外の添付ファイルを送るための拡張仕様 (マイム)', 'Used by email systems to handle file attachments and rich content.', ', Sending a photo.jpg via email , Receiving PDF attachment in Outlook , Embedding images directly in email body', 'Email attachments and rich content support.', 'メール添付ファイルの仕様', false),,
  (167, 6, 'NNTP (Network News Transfer Protocol)', '', 'A protocol used for reading and posting articles to Usenet newsgroups (early internet forums).', 'ネットニュース(Usenet)の記事を配信するプロトコル (エヌエヌティーピー)', 'Used by Usenet servers and newsreader clients (now largely obsolete).', ', Reading alt.comp.freeware discussions , Downloading binaries from Usenet groups , News server syncing between providers', 'Old internet forum protocol.', '昔のネット議論掲示板の仕組み', false),,
  (168, 6, 'NTP (Network Time Protocol)', '', 'A protocol for synchronizing computer clocks over a network to a reference time source (e.g., atomic clocks).', 'ネットワーク上の機器の時刻を正確に同期するプロトコル (エヌティーピー)', 'Used to ensure logs, transactions, and authentication have accurate timestamps.', ', Windows syncing time with time.windows.com , Bank server matching timestamp to millisecond , Authentication failing if client/server clocks mismatch', 'Keeps all devices on same clock.', 'ネットワーク時刻同期の仕組み', false),,
  (169, 6, 'POP (Post Office Protocol)', '', 'A protocol for retrieving emails from a server, typically downloading and deleting them from the server.', 'サーバからメールをダウンロードして受信するプロトコル (ポップ)', 'Used by email clients where users want to store mail locally and free server space.', ', Downloading all emails to Outlook then deleting from server , Reading mail offline after download , Simple email setup on older systems', 'Download email, often delete from server.', 'メールをダウンロードする方法', false),,
  (170, 6, 'PPP (Point-to-Point Protocol)', '', 'A data link protocol used to establish direct network connections between two nodes (e.g., computer to ISP via modem).', '2点間を直接接続するための通信プロトコル (ピーピーピー)', 'Used historically for dial-up internet connections, VPNs, and DSL.', ', 56k modem dial-up connecting to AOL , PPPoE for fiber internet authentication , VPN tunnel establishment', 'Direct connection between two points.', '1対1の接続を確立する', false),,
  (171, 6, 'S/MIME (Secure/Multipurpose Internet Mail Extensions)', '', 'A standard for public key encryption and digital signing of email messages, adding security to MIME.', 'MIMEに暗号化と電子署名を追加した安全なメール仕様 (エス/マイム)', 'Used by corporate and government email for end-to-end encryption and authentication.', ', Sending encrypted email only recipient can read , Digitally signing email to prove it''s from you and not altered , Government inter-office secure communication', 'Secure version of email attachments and content.', '暗号化と署名のメール拡張', false),,
  (172, 6, 'SMTP (Simple Mail Transfer Protocol)', '', 'The standard protocol for sending emails from a client to a server or between mail servers.', 'メールを送信するための標準プロトコル (エスエムティーピー)', 'Used whenever you send an email (not receiving).', ', Gmail sending your message to recipient''s server , Mail server to mail server delivery , WordPress contact form emailing you', 'Email sending and relaying protocol.', 'メール送信の標準手順', false),,
  (173, 6, 'SNMP (Simple Network Management Protocol)', '', 'A protocol for monitoring and managing network devices like routers, switches, servers, and printers.', 'ネットワーク機器を監視・管理するためのプロトコル (スニンプ)', 'Used by network administrators to check device health, bandwidth, and errors.', ', Monitoring router CPU usage and temperature , Printer alerting when toner is low , SolarWinds tracking network performance', 'Remote health check for network devices.', 'ネットワーク監視の仕組み', false),,
  (174, 6, 'SSH (Secure Shell)', '', 'A cryptographic network protocol for secure remote login and command execution over unsecured networks.', '暗号化を使って安全にリモート接続するプロトコル (エスエスエイチ)', 'Used by system administrators to manage servers securely (replaces Telnet).', ', ssh user@server.com to access cloud server , SCP for secure file copy , Port forwarding for encrypted tunnel', 'Secure remote terminal access with encryption.', '安全なリモート接続方法', false),,
  (175, 6, 'SSL (Secure Sockets Layer)', '', 'An older cryptographic protocol for encrypting internet connections (superseded by TLS but still commonly used in naming).', 'Web通信を暗号化するプロトコル (エスエスエル / TLSに進化)', 'Used to secure HTTPS websites, though modern systems use TLS. Still called SSL certificate commonly.', ', Padlock icon in browser address bar , E-commerce checkout page encryption , SSL Certificate purchased for websites', 'Old name for web encryption (now TLS).', '暗号化通信の旧名(現TLS)', false),,
  (176, 6, 'TCP (Transmission Control Protocol)', '', 'A reliable, connection-oriented protocol that ensures data packets are delivered in order and without errors.', '確実に順番通り届ける信頼性重視のプロトコル (ティーシーピー)', 'Used for applications where data integrity matters: web, email, file transfer.', ', Loading a complete webpage without missing parts , Downloading a file with automatic retransmission of lost packets , Email delivery guaranteeing all text arrives', 'Reliable, in-order delivery with error check.', '確実にデータを届ける方式', false),,
  (177, 6, 'TELNET (Teletype Network)', '', 'An older protocol for remote terminal access over a network, now largely replaced by SSH due to lack of encryption.', 'リモートでコンピュータを操作する旧式プロトコル (テルネット)', 'Used rarely today, mostly for legacy systems or local debugging (unencrypted, so insecure).', ', Connecting to old mainframe at a university , Troubleshooting router on local network without encryption , Testing manual HTTP requests to a server', 'Old unencrypted remote terminal access.', '暗号化なしのリモート接続(旧式)', false),,
  (178, 6, 'UDP (User Datagram Protocol)', '', 'A fast, connectionless protocol that sends packets without guaranteeing delivery or order (no retransmission).', '速さ重視で届かない可能性もあるプロトコル (ユーザーデータグラムプロトコル / ユーディーピー)', 'Used for real-time applications where speed beats perfection: streaming, gaming, VoIP.', ', Zoom video call: missing few pixels better than delay , Online game: player positions update fast even if one packet lost , DNS lookup query (fast, short message)', 'Fast, fire-and-forget data delivery.', '速いが届かないこともある通信', false),,
  (179, 6, 'WPA2 (Wi-Fi Protected Access 2)', '', 'A security protocol for Wi-Fi networks that uses AES encryption for strong protection (replaced WEP and WPA).', 'Wi-Fiネットワークを守る暗号化規格 (ダブリュピーエーツー)', 'Used on most home and office Wi-Fi routers to prevent unauthorized access and eavesdropping.', ', Entering password for HomeWiFi on phone (WPA2) , Office Wi-Fi requiring WPA2 enterprise with username , Router configuration showing WPA2-PSK option', 'Standard Wi-Fi password security today.', '現在のWi-Fi暗号化標準', false);;